### ISSUE TITLE
Won't run in Xcode 16 on macOS 15 Sequoia

### ISSUE THREAD

**Issue by ndjdev** [Mobile-Telematics/TelematicsApp-iOS#2]
We can't get this project to run on Xcode 16 on macOS 15 Sequoia on an M1 Pro MBP. Summary of the steps taken:

1. Clone repository
2. Save `GoogleService-Info.plist` from our Firebase account (Android app is working fine after following instructions)
3. Update instance ID and key in `Configurator`
4. Try and build for iPhone 16

The errors we get are as follows:

- <snipped>TelematicsApp/TelematicsApp-Bridging-Header.h
  - failed to emit precompiled header '/Users/user/Library/Developer/Xcode/DerivedData/TelematicsApp-hftzxfeaqzgjfgbfnqwqxlkrzyrb/Build/Intermediates.noindex/PrecompiledHeaders/TelematicsApp-Bridging-Header-swift_3G6HR7P5KU5Y7-clang_3O1PV07VGL6NI.pch' for bridging header '<snipped>TelematicsApp/TelematicsApp-Bridging-Header.h'
  - could not build module 'MagicalRecord'
- <snipped>Pods/MagicalRecord/MagicalRecord/Core/MagicalRecordLogging.h
  - <snipped>Pods/MagicalRecord/MagicalRecord/Core/MagicalRecordLogging.h:28:13 could not build module 'CocoaLumberjack'
- /Users/user/Library/Developer/Xcode/DerivedData/TelematicsApp-hftzxfeaqzgjfgbfnqwqxlkrzyrb/Build/Products/Debug-iphonesimulator/CocoaLumberjack/CocoaLumberjack.framework/Headers/CocoaLumberjack-Swift.h
  - unsupported Swift architecture

Any light you can shed would be really appreciated.

Thanks

**Comment by telematicsgig** [comment]
Hi Nick,

Thank you for bringing this issue to our attention. We’ll review it and get back to you with a solution soon.

**Comment by sgusakovsky** [comment]
Hello @nickdjones Thank you for your feedback. We've fixed current issue. You just need to pull the latest commit of master branch
